name: Maven Package Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true
        default: ""
      developmentVersion:
        description: "Snapshot version"
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        java-package: 'jdk'
        cache: 'maven'
        server-id: central
        server-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        server-password: ${{ secrets.MAVEN_CENRAL_TOKEN }}
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    - name: Verify Whether a Release is Ready
      id: release
      shell: bash
      run: |
        if [ "${{ github.event.inputs.releaseVersion }}" != "" ] && [ "${{ github.event.inputs.developmentVersion }}" != "" ]; then
          echo "auto_release=true" >> $GITHUB_ENV
        else
          echo "auto_release=false" >> $GITHUB_ENV
        fi
    - name: Verify integrity
      run: |
        mvn -Prelease verify
    - name: Release With Maven
      run: |
        mvn release:prepare \
          release:perform \
          -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
          -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
      env:
        AUTO_RELEASE_AFTER_CLOSE: ${{ env.auto_release }}
    - name: Artifact Name
      shell: bash
      run: |
        echo "artifact_name=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> "$GITHUB_ENV"
    - name: Define Jar Name
      shell: bash
      run: |
        echo "{{ env.artifact_name }}"
        ls -al ./target/
        mv ./target/*.*:${{ env.artifact_name }}.jar ./target/${{ env.artifact_name }}.jar
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.artifact_name }}-${{ env.sha_short }}
        path: ./target/${{ env.artifact_name }}.jar
    - name: Workflow Release Notes
      uses: peter-evans/repository-dispatch@v2
      if: ${{ github.event.inputs.releaseVersion }} != "" && ${{ github.event.inputs.developmentVersion }} != ""
      with:
        event-type: release-notes
        client-payload: '{"auto_release": "${{ env.auto_release }}", "artifact": "${{ env.artifact_name }}-${{ env.sha_short }}"}'
